basePath: /api
definitions:
  actions.CreateRequest:
    properties:
      amount:
        description: payment amount (optional)
        type: number
      asset_id:
        description: payment asset id (optional)
        format: uuid
        type: string
      follow_id:
        description: follow id to track tx (uuid)
        format: uuid
        type: string
      parameters:
        description: tx parameters
        items:
          type: string
        type: array
      user_id:
        format: uuid
        type: string
    type: object
  actions.CreateResponse:
    properties:
      code:
        description: multisig payment code
        type: string
      code_url:
        description: multisig payment code url
        type: string
      memo:
        description: payment memo
        type: string
    type: object
  api.Asset:
    properties:
      chain:
        $ref: '#/definitions/api.Asset'
      chain_id:
        type: string
      id:
        description: mixin asset id
        type: string
      logo:
        type: string
      name:
        type: string
      price:
        type: string
      symbol:
        type: string
    type: object
  api.Resp_ListAssets:
    properties:
      assets:
        items:
          $ref: '#/definitions/api.Asset'
        type: array
    type: object
  system.InfoResponse:
    properties:
      members:
        description: multisig members
        items:
          type: string
        type: array
      oauth_client_id:
        description: oauth client id
        format: uuid
        type: string
      public_key:
        type: string
      threshold:
        description: multisig threshold
        type: integer
    type: object
  system.TimeResponse:
    properties:
      epoch:
        type: integer
      iso:
        type: string
    type: object
  user.LoginRequest:
    properties:
      code:
        description: mixin oauth code
        type: string
    type: object
  user.LoginResponse:
    properties:
      avatar:
        description: user avatar
        type: string
      id:
        description: user mixin id
        format: uuid
        type: string
      name:
        description: user name
        type: string
      scope:
        description: mixin oauth scope
        type: string
      token:
        description: mixin oauth token
        type: string
    type: object
  views.Error:
    properties:
      code:
        type: integer
      msg:
        type: string
    type: object
host: pando-test-api.fox.one
info:
  contact:
    email: support@pando.im
    name: API Support
    url: http://www.pando.im/support
  description: Pando Api Doc
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://pando.im/terms/
  title: Pando API
  version: "1.0"
paths:
  /actions:
    post:
      consumes:
      - application/json
      parameters:
      - description: request payments
        in: body
        name: request
        schema:
          $ref: '#/definitions/actions.CreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/actions.CreateResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/views.Error'
      summary: request payment code
      tags:
      - actions
  /assets:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Resp_ListAssets'
        default:
          description: ""
          schema:
            $ref: '#/definitions/views.Error'
      summary: list assets
      tags:
      - assets
  /info:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/system.InfoResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/views.Error'
      summary: Show system info
      tags:
      - system
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: request login
        in: body
        name: request
        schema:
          $ref: '#/definitions/user.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.LoginResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/views.Error'
      summary: login with mixin oauth code
      tags:
      - user
  /time:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/system.TimeResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/views.Error'
      summary: Show server time
      tags:
      - system
schemes:
- https
swagger: "2.0"
